### ISSUE TITLE
Sticky typed filter (Feature request)

### ISSUE THREAD

**Issue by Knito58** [iMoonDay/OnlyNeedOneChest#10]
The filter can be cleared with right clicking, which is very EMI / REI / JEI like. But it is lost after opening the GUI.
The click-filters on the right side of the accessor GUI already are sticky. After opening the GUI the last filters are still set.

How about making the typed filter in the input field sticky, too? This would totally mimic the recipe mods and it would make your GUI more consistent.

At the moment the **click-filters are sticky but the typed filter is not**. This is a little bit inconsistent.

Then all filters would be sticky. I would not need to re-type my input all the time when I re-open the GUI.

**Comment by iMoonDay** [comment]
I'll add an new setting option to choose whether they are sticky or not

**Comment by Knito58** [comment]
Yes that is even better than my suggestion. Then the click-filter should be selectable as sticky or not, too.

**Comment by Knito58** [comment]
Yes. Great. Works perfectly. Thank you.
