### ISSUE TITLE
Double Chest issue with memory converter

### ISSUE THREAD

**Issue by Knito58** [iMoonDay/OnlyNeedOneChest#5]
If the game decides a part of the double chest being the second, then the memory converter may always be green and not show the contents in the access points when this second part of the chest does not yet contain anything. Also when a double chest is filled up only the part being connected to ON1 seems to be counted and displayed.

This certainly has some advantages on the programming side as you can treat all inventories the same way but makes parts of storage inaccessible.

**Comment by iMoonDay** [comment]
This has been fixed in the latest version

**Comment by Knito58** [comment]
Yes it is. Thank you.
