### ISSUE TITLE
Client-side mixin being loaded on both sides

### ISSUE THREAD

**Issue by unilock** [iMoonDay/OnlyNeedOneChest#6]
https://github.com/iMoonDay/OnlyNeedOneChest/blob/7d2b44a5d21fc48d89a041d7d0e546fef99bd1dd/src/main/resources/on1chest.mixins.json#L9

`net.minecraft.data.client.ModelProvider` is a client-side only class, but the mixin targeting it is loaded on both client and server :(

(what does the mixin do, anyway...?)

**Comment by iMoonDay** [comment]
This is a fix mixin to prevent errors from being reported when executing Data Generation, it doesn't do anything for the mod, I just forgot to remove it at build time.
