### ISSUE TITLE
Filter type "Blocks" in accessor not shows only blocks (bug)

### ISSUE THREAD

**Issue by Knito58** [iMoonDay/OnlyNeedOneChest#8]
The optional filters on the right side of an accessor are very cool feature. Damaged, Enchanted and NBT data are my favourites to quickly find any tool or weapon. That is great.

Ingredients is a big question mark to me as nearly everything in minecraft may be an ingredient at some point.

However, the blocks filter just not works correctly. A flower is not a block neither is wheat. There is a little error inside. It filters some items out but there is still too much non-block-stuff left.

**Comment by iMoonDay** [comment]
Ingredient filtering essentially displays items from the ingredient group in the Creative Mode inventory.

As for the definition of a block, in the code, anything that can be placed is considered a block, so flowers are also considered blocks.

Perhaps you want to categorize them further?

**Comment by Knito58** [comment]
mmmh.... this looks like the ingredients filter somehow. I don't know. Maybe putting a regex on it like .*block$
and if the MC name is containing "block" then its a block.
I thought "blocks" were things which you would take for building. But yes, everything in the list is good for building. In my brain "blocks" are cubic. But there is no "cubic" tag in MC. That is difficult. If I made up my mind for a very long regex worm, would you consider taking that into the blocks filter?

**Comment by iMoonDay** [comment]
I could add a custom filtering feature, such as using regular expressions to match items' IDs or names.

In fact, it’s quite easy in the code to distinguish whether a block is cubic or not.

I think we could enhance the filter by adding subtypes, allowing users to specifically select cubes, slabs, or other non-cubic blocks.

**Comment by Knito58** [comment]
That would be handy for building as you would not have to type. Just click on "stairs" and bingo. But maybe a regex entry field would make up for this. But then again, people like me would ask you all the time what to enter here. Forget about the regex field.

**Comment by Knito58** [comment]
If cubic is that easy, why not just add "cubic" filter and dismiss "blocks" and "ingredients"?

**Comment by Knito58** [comment]
Ingredients and blocks are not needed as filter as they do not really shrink the result. The filter value is not as high as ie "Redstone" or "Damaged". These are high values imho. So if a cubic filter would shrink the result to cubic building blocks this could probably please many users.

**Comment by iMoonDay** [comment]
I'm now considering redoing the filtering feature. For example, customizing filters, hiding infrequently used filters and subcategory filters.

**Comment by iMoonDay** [comment]
You can join my [Discord](https://discord.gg/6udWKdaH5Y) if you want to be further involved in subsequent revisions. It's just too inconvenient to reply here.

**Comment by Knito58** [comment]
The new filter options are great! Thank you.
