### ISSUE TITLE
Items in extended drawers do not show up

### ISSUE THREAD

**Issue by Knito58** [iMoonDay/OnlyNeedOneChest#9]
![nologs](https://github.com/user-attachments/assets/6326f755-73d4-4cd5-bb9b-23eb4797223f)
I have connected a memory converter to an extended drawer accessor. The items in the inventory do not show up. There are 1024 oak logs in the drawer but only the 76 oak logs which were already in the system do show up.

MC 1.20.1 Fabric
Extended Drawers v2.1.1+mc.1.20.1
Only Need One Chest v1.1.0+1.20.1

**Comment by iMoonDay** [comment]
The memory converter will only take effect for the one container towards which it is directed and will not be connected to other containers.

**Comment by Knito58** [comment]
![nologs2](https://github.com/user-attachments/assets/7edc122a-499d-4cec-9845-8ff99454996b)
Ok then putting the connector on the drawers has also no effect.

**Comment by iMoonDay** [comment]
I just looked at the code of the drawer, and it doesn't implement a universal container, but implements its own storage method, so the memory converter cannot recognize it

**Comment by Knito58** [comment]
Yes I thought it would be easy as I can put a vanilla hopper under a drawer or access block of that mod and get the content into normal chests or barrels. The "Only need 1 chest" mod is very super and one would easily get around this by putting hoppers under the drawers with the desired content. This is ok as it is. I tried to look into the code and did not understand much. Feeling silly now.
We may just close this. It is not an issue, just a feature request. 
Minecraft is all about building. We can get around this by putting some more blocks into the world.

**Comment by iMoonDay** [comment]
The original intention behind creating this mod was to allow players to only need to install my storage mod, which is why I named it "Only Need One Chest".
So I'm not planning on deep compatibility with other storage mods.

**Comment by iMoonDay** [comment]
I suddenly had an idea. I'm planning to add a display storage block, with functionality similar to the drawer.
It would be something like a combination of a glass storage memory block and a drawer.
What do you think?

**Comment by Knito58** [comment]
This sounds interesting. I have Jade installed and can already see an overview of what is contained in storage blocks. I do access the storage system's contents only through the interfaces. If there are many different things inside a storage block then there is no  gain in my opinion: I will see clutter. But it sounds very stylish.
Now I have an idea for another feature. But this will be a new issue so that you can close this one.
